### ISSUE TITLE
Evernote got an error: The operation couldn’t be completed. Operation not permitted"

### ISSUE THREAD

**Issue by dtournemille** [jamietr1/evernote-backup#1]
Do you know if this script still functions under Evernote 6.0? I'm receiving an error on the "export matches to f" line.

**Comment by wendyyuchensun** [comment]
have the same problem with the version of Evernote app recommended in the [README.md](https://github.com/jamietr1/evernote-backup) file~

![untitled](https://cloud.githubusercontent.com/assets/13805499/14310132/f58f4422-fc12-11e5-95a1-ebea94188ea2.png)
