### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by siggysamson** [jamietr1/evernote-backup#3]
Hi @jamietr1,
I really like your Evernote Backup script. I created a fork from it and updated the README as well as the script itself to store the enex file in the same directory as the script is running (as this is matching my personal use case better): https://github.com/siggysamson/evernote-backup

As you are hosting this script on Github I think you intend this to be open source. But what I'm missing in this repository is a proper license. You can also take a look into http://choosealicense.com to add one.
I can also create a pull request with my changes but I'm not sure if you want those changes to be applied.

Let me know.

Thanks!

**Comment by jamietr1** [comment]
Sammy,

I'm delighted to hear you found the script useful. Thanks for reminding me
about the missing license file. I've just gone ahead and added one
(standard MIT), so you should see it in my repo now.

Best,

J

---

Jamie Todd Rubin (@jamietr http://twitter.com/jamietr)
http://www.jamietoddrubin.com
http://www.jamietoddrubin.com/going-paperless/

**Comment by siggysamson** [comment]
Hi Jamie,

thanks for adding the license!
